sudo: false

services:
  - mongodb

language: go

go:
  - 1.7.3

before_install:
  - go get github.com/Masterminds/glide

install:
  - glide install
  - export GOPATH=$(pwd):$GOPATH
  - echo $(pwd)
  - echo $GOPATH

script:
  make travis
